In [1]:
import pandas as pd 
import os
from timezonefinder import TimezoneFinder
from tqdm import tqdm

tqdm.pandas()

obj = TimezoneFinder()

In [21]:
df = pd.read_csv('metadata_v3.csv')
df.set_index("image_id")

,id,date,time,day_of_week,location,location_displayed,location_id,new_lat,new_lng,activity,activity_id,event_id,caption,ocr,object_tags,video_id,image_available
image_id,,,,,,,,,,,,,,,,,
201901/01/20190101_103717_000,1,2019-01-01,10:37,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,53.389980,-6.145760,watching tv,0,0,a window with curtains and a picture of a chair,'口',"curtain,house,bed",20190101,1
201901/01/20190101_103749_000,2,2019-01-01,10:37,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,53.389980,-6.145760,watching tv,0,0,a cabinet with a shelf and a mirror on it,No OCR,"house,cup",20190101,1
201901/01/20190101_103821_000,3,2019-01-01,10:38,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,53.389980,-6.145760,watching tv,0,1,a window with a view of a house in the backgro...,No OCR,"window,house",20190101,1
201901/01/20190101_103853_000,4,2019-01-01,10:38,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,53.389980,-6.145760,cooking,1,2,a kitchen with a skylight and a bowl of fruit.,No OCR,"human face,girl,dining table,bottle,clothing,p...",20190101,1
201901/01/20190101_103925_000,5,2019-01-01,10:39,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,53.389980,-6.145760,working on computer,2,3,a computer monitor sitting on top of a desk.,No OCR,"computer keyboard,keyboard,mouse,laptop,tv,book",20190101,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202006/30/20200630_211803_000,725945,2020-06-30,22:18,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",9737,53.389959,-6.145810,watching tv,100865,283,a person's face in the dark,No OCR,NaN,20200630,1
202006/30/20200630_211908_000,725946,2020-06-30,22:19,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",9737,53.389961,-6.145818,watching tv,100865,283,a picture of a screen with a picture of a pers...,No OCR,"laptop,tv",20200630,1
202006/30/20200630_212119_000,725947,2020-06-30,22:21,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",9737,53.389973,-6.145777,watching tv,100865,283,the dark room is very dark and it is dark and ...,No OCR,NaN,20200630,1
202006/30/20200630_212152_000,725948,2020-06-30,22:21,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",9737,53.389973,-6.145777,watching tv,100865,283,a dark room with a blue light,No OCR,NaN,20200630,1
202006/30/20200630_212225_000,725949,2020-06-30,22:22,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",9737,53.389962,-6.145813,Other,-1,-1,a dark room with a white wall and a black wall.,No OCR,NaN,20200630,1

In [22]:
def safe_timezone_lookup(x):
    if pd.notna(x["new_lat"]) and pd.notna(x["new_lng"]):
        try:
            return obj.timezone_at(lat=x["new_lat"], lng=x["new_lng"])
        except Exception as e:
            return None  # or log the error
    else:
        return None

df["timezone"] = df.progress_apply(safe_timezone_lookup, axis=1)

100%|██████████| 725949/725949 [01:31<00:00, 7953.54it/s]

In [24]:
df.rename(columns={"date": "utc_date", "time": "utc_time"}, inplace=True)

In [32]:
df.set_index("image_id", inplace=True)

In [36]:
def time_to_hhmmss(x):
    if pd.notna(x):
        try:
            time_str = x.split("_")[-2]
            return time_str[:2] + ":" + time_str[2:4] + ":" + time_str[4:6]
        except Exception as e:
            return None  # or log the error
    else:
        return None

df["utc_time"] = df.index.to_series().progress_apply(time_to_hhmmss)

df["utc_date"] = df["utc_date"].astype(str)
df["utc_time"] = df["utc_time"].astype(str)

100%|██████████| 725949/725949 [00:01<00:00, 536863.30it/s]

In [37]:
df.head()

,id,utc_date,utc_time,day_of_week,location,location_displayed,location_id,new_lat,new_lng,activity,activity_id,event_id,caption,ocr,object_tags,video_id,image_available,timezone
image_id,,,,,,,,,,,,,,,,,,
201901/01/20190101_103717_000,1,2019-01-01,10:37:17,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,53.38998,-6.14576,watching tv,0,0,a window with curtains and a picture of a chair,'口',"curtain,house,bed",20190101,1,Europe/Dublin
201901/01/20190101_103749_000,2,2019-01-01,10:37:49,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,53.38998,-6.14576,watching tv,0,0,a cabinet with a shelf and a mirror on it,No OCR,"house,cup",20190101,1,Europe/Dublin
201901/01/20190101_103821_000,3,2019-01-01,10:38:21,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,53.38998,-6.14576,watching tv,0,1,a window with a view of a house in the backgro...,No OCR,"window,house",20190101,1,Europe/Dublin
201901/01/20190101_103853_000,4,2019-01-01,10:38:53,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,53.38998,-6.14576,cooking,1,2,a kitchen with a skylight and a bowl of fruit.,No OCR,"human face,girl,dining table,bottle,clothing,p...",20190101,1,Europe/Dublin
201901/01/20190101_103925_000,5,2019-01-01,10:39:25,Tuesday,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",0,53.38998,-6.14576,working on computer,2,3,a computer monitor sitting on top of a desk.,No OCR,"computer keyboard,keyboard,mouse,laptop,tv,book",20190101,1,Europe/Dublin

In [38]:
import pandas as pd
import pytz
from datetime import datetime

def convert_to_local_time(row):
    if pd.isna(row["timezone"]):
        return None

    try:
        # Combine UTC day and UTC time into one datetime
        utc_str = f"{row['utc_date']} {row['utc_time']}"
        utc_dt = datetime.strptime(utc_str, "%Y-%m-%d %H:%M:%S")
        utc_dt = pytz.utc.localize(utc_dt)

        # Convert to local time using timezone string
        local_tz = pytz.timezone(row["timezone"])
        local_dt = utc_dt.astimezone(local_tz)

        return local_dt
    except Exception as e:
        return None
    

df["temp_local_time"] = df.progress_apply(convert_to_local_time, axis=1)

100%|██████████| 725949/725949 [00:28<00:00, 25359.95it/s]

In [42]:
df["temp_local_time"].value_counts()
df["local_date"] = df["temp_local_time"].apply(lambda x: str(x).split(" ")[0] if pd.notna(x) else None)
df["local_time"] = df["temp_local_time"].apply(lambda x: str(x).split(" ")[1][:8] if pd.notna(x) else None)

In [48]:
df = df.drop(columns=["temp_local_time"])

In [49]:
cols = [
    "id",
    "utc_date", "utc_time", 
    "timezone",
    "local_date", "local_time",
    "day_of_week",
    "new_lat", "new_lng"
]

# Add any remaining columns not explicitly listed
remaining_cols = [col for col in df.columns if col not in cols]
new_df = df[cols + remaining_cols]

In [55]:
new_df.sample(20)

,id,utc_date,utc_time,timezone,local_date,local_time,day_of_week,new_lat,new_lng,location,location_displayed,location_id,activity,activity_id,event_id,caption,ocr,object_tags,video_id,image_available
image_id,,,,,,,,,,,,,,,,,,,,
202001/14/20200114_181413_000,533908,2020-01-14,18:14:13,Asia/Bangkok,2020-01-15,01:14:13,Tuesday,13.735666,100.556204,"Citadines Sukhumvit 8 Bangkok, Residential Bui...","Citadines Sukhumvit 8 Bangkok, Bangkok, Thailand",7575,working on computer,53287,696,a bed with a computer on top of it.,No OCR,"tv,bed",20200114,1
202005/08/20200508_093903_000,657303,2020-05-08,09:39:03,Europe/Dublin,2020-05-08,10:39:03,Friday,53.385640,-6.257713,"Dublin City University (DCU), College and Univ...","Dublin City University (DCU), Dublin, Ireland,...",9028,working on computer,94838,60,a person is holding a phone in front of a comp...,No OCR,"human face,person,tv",20200508,1
201904/08/20190408_121749_000,128897,2019-04-08,12:17:49,Europe/Dublin,2019-04-08,13:17:49,Monday,53.385524,-6.257882,"Dublin City University (DCU), College and Univ...","Dublin City University (DCU), Dublin, Ireland,...",1895,working on computer,12382,144,a computer monitor sitting on top of a desk.,No OCR,"window,desk,keyboard,cup,laptop,tv,office buil...",20190408,1
201901/02/20190102_141818_000,1690,2019-01-02,14:18:18,Europe/Dublin,2019-01-02,14:18:18,Wednesday,53.153147,-6.915929,"Kildare Village, Outlet Mall, , Kildare, Irela...","Kildare Village, Kildare, Ireland, Kildare — N...",41,eating,138,175,a woman sitting at a table in a restaurant.,No OCR,"human face,dining table,bottle,clothing,person...",20190102,1
201911/19/20191119_111932_000,443073,2019-11-19,11:19:32,Europe/Madrid,2019-11-19,12:19:32,Tuesday,40.547763,-3.692128,"Autonomous University of Madrid, , , Área metr...","Autonomous University of Madrid, Madrid, Commu...",6334,watching tv,40927,195,a person is holding a watch in a room.,No OCR,"human face,person,man",20191119,1
201907/24/20190724_074230_000,255434,2019-07-24,07:42:30,Europe/Dublin,2019-07-24,08:42:30,Wednesday,53.385535,-6.257141,"Dublin City University (DCU), College and Univ...","Dublin City University (DCU), Dublin, Ireland,...",4112,working on computer,24429,47,a computer monitor sitting on top of a desk.,No OCR,"computer monitor,desk,cell phone,cup,tv,fork,o...",20190724,1
201908/29/20190829_220838_000,314748,2019-08-29,22:08:38,Europe/Dublin,2019-08-29,23:08:38,Thursday,53.389948,-6.145831,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",4928,watching tv,30578,349,a picture of a window in a room.,No OCR,"window,picture frame,tv",20190829,1
202004/26/20200426_130339_000,642105,2020-04-26,13:03:39,Europe/Dublin,2020-04-26,14:03:39,Sunday,53.389951,-6.145772,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",8919,Other,93446,53,a laptop computer sitting on top of a desk.,No OCR,NaN,20200426,1
201902/01/20190201_163845_000,43582,2019-02-01,16:38:45,Europe/Dublin,2019-02-01,16:38:45,Friday,53.385505,-6.257230,"Dublin City University (DCU), College and Univ...","Dublin City University (DCU), Dublin, Ireland,...",641,Other,4250,204,a blurry photo of a room with a bunch of cubic...,No OCR,"tv,chair,building",20190201,1
201912/26/20191226_162026_000,513348,2019-12-26,16:20:26,Europe/Dublin,2019-12-26,16:20:26,Thursday,52.514563,-6.662599,"Unknown Place, , , Wexford, Ireland, The Munic...","Unknown Place, Wexford, Ireland, Enniscorthy",7184,eating,47176,221,a light fixture hanging from a ceiling in a room.,No OCR,NaN,20191226,1
201912/24/20191224_130622_000,509848,2019-12-24,13:06:22,Europe/Dublin,2019-12-24,13:06:22,Tuesday,53.389984,-6.145804,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",7131,watching tv,46777,235,a keyboard and a computer monitor on a desk.,No OCR,"computer monitor,desk,computer keyboard,keyboa...",20191224,1
202003/01/20200301_133203_000,570560,2020-03-01,13:32:03,Europe/Dublin,2020-03-01,13:32:03,Sunday,53.389981,-6.145788,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",8058,driving car,71547,344,a picture of a tv on a wall in a living room.,No OCR,"window,microwave,laptop,tv,vase,potted plant,o...",20200301,1
201908/27/20190827_220320_000,309786,2019-08-27,22:03:20,Europe/Dublin,2019-08-27,23:03:20,Tuesday,53.386706,-6.147243,"Charm Hand & Foot Spa, , , Dublin, Ireland, Le...","Charm Hand & Foot Spa, Dublin, Ireland, Leinster",4896,watching tv,30145,357,a white wall with a white wall and a phone on it.,No OCR,"chair,book",20190827,1
201909/12/20190912_170518_000,347909,2019-09-12,17:05:18,Europe/Dublin,2019-09-12,18:05:18,Thursday,53.389980,-6.145803,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",5293,watching tv,33717,342,a skylight in a room with a skylight,No OCR,window,20190912,1
202005/17/20200517_065958_000,669678,2020-05-17,06:59:58,Europe/Dublin,2020-05-17,07:59:58,Sunday,53.389932,-6.145686,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",9122,cooking,95714,36,a view of the skylight in the ceiling.,No OCR,window,20200517,1
201907/03/20190703_214240_000,217615,2019-07-03,21:42:40,Europe/Dublin,2019-07-03,22:42:40,Wednesday,53.390004,-6.145791,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",3534,Other,20959,581,a skylight in a living room with a tv,No OCR,"picture frame,tv",20190703,1
201903/26/20190326_195639_000,112056,2019-03-26,19:56:39,Europe/Dublin,2019-03-26,19:56:39,Tuesday,53.389873,-6.145488,"HOME, , , Dublin, Ireland, Leinster","HOME, Dublin, Ireland, Leinster",1638,watching tv,10547,266,a metal railing in a dark room with a light on.,No OCR,bird,20190326,1
201902/01/20190201_191354_000,43829,2019-02-01,19:13:54,Europe/Dublin,2019-02-01,19:13:54,Friday,53.345603,-6.258497,"The Westin Dublin, Lodging, , Dublin, Ireland,...","The Westin Dublin, Dublin, Ireland, Leinster",649,Other,4267,249,the hotel is located in the heart of the city.,No OCR,"window,building",20190201,1
201912/14/20191214_165141_000,491471,2019-12-14,16:51:41,Europe/Dublin,2019-12-14,16:51:41,Saturday,53.388916,-6.074695,"The Bloody Stream, Pub, Restaurant, , Dublin, ...","The Bloody Stream, Dublin, Ireland, Leinster",6795,Other,44884,317,a group of people sitting around a table with ...,No OCR,"human face,wine glass,dining table,cup,person,...",20191214,1
201912/01/20191201_104303_000,466731,2019-12-01,10:43:03,Europe/Dublin,2019-12-01,10:43:03,Sunday,53.389987,-6.145824,"Car, , , Dublin, Ireland, Leinster","Car, Dublin, Ireland, Leinster",6530,Other,42754,139,a car parked in front of a house,No OCR,"window,person,potted plant,wheel,tire,car,house",20191201,1

In [57]:
new_df.to_csv("metadata_v4.csv", index=True)

In [58]:
n = pd.read_csv("metadata_v4.csv")
n.head()

,image_id,id,utc_date,utc_time,timezone,local_date,local_time,day_of_week,new_lat,new_lng,...,location_displayed,location_id,activity,activity_id,event_id,caption,ocr,object_tags,video_id,image_available
0,201901/01/20190101_103717_000,1,2019-01-01,10:37:17,Europe/Dublin,2019-01-01,10:37:17,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,watching tv,0,0,a window with curtains and a picture of a chair,'口',"curtain,house,bed",20190101,1
1,201901/01/20190101_103749_000,2,2019-01-01,10:37:49,Europe/Dublin,2019-01-01,10:37:49,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,watching tv,0,0,a cabinet with a shelf and a mirror on it,No OCR,"house,cup",20190101,1
2,201901/01/20190101_103821_000,3,2019-01-01,10:38:21,Europe/Dublin,2019-01-01,10:38:21,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,watching tv,0,1,a window with a view of a house in the backgro...,No OCR,"window,house",20190101,1
3,201901/01/20190101_103853_000,4,2019-01-01,10:38:53,Europe/Dublin,2019-01-01,10:38:53,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,cooking,1,2,a kitchen with a skylight and a bowl of fruit.,No OCR,"human face,girl,dining table,bottle,clothing,p...",20190101,1
4,201901/01/20190101_103925_000,5,2019-01-01,10:39:25,Europe/Dublin,2019-01-01,10:39:25,Tuesday,53.38998,-6.14576,...,"HOME, Dublin, Ireland, Leinster",0,working on computer,2,3,a computer monitor sitting on top of a desk.,No OCR,"computer keyboard,keyboard,mouse,laptop,tv,book",20190101,1