In [7]:
import pandas as pd

In [8]:
df1 = pd.read_csv("./MVK_keyframe_to_time_mapping.csv")
df2 = pd.read_csv("./MVK2_keyframe_to_time_mapping.csv")

# concatenate the two dataframes
df = pd.concat([df1, df2], ignore_index=True)
df.head()

             video_id  keyframe_id  timeframe
0  Ambon_Apr2012_0001            1      0.000
1  Ambon_Apr2012_0001            2      1.001
2  Ambon_Apr2012_0001            3      2.002
3  Ambon_Apr2012_0001            4      3.003
4  Ambon_Apr2012_0001            5      4.004

In [9]:
# add id column starting from 1
# add image_id column: "MVK/{video_id}/{keyframe_id:05d}.jpg"
df['id'] = df.index + 1
df['image_id'] = df.apply(lambda row: f"MVK/{row['video_id']}/{row['keyframe_id']:05d}", axis=1)
df['start_time'] = df['timeframe']
df['end_time'] = df['timeframe']
df = df[['id', 'image_id', 'video_id', 'keyframe_id', 'start_time', 'end_time']]

df.head()

,id,image_id,video_id,keyframe_id,start_time,end_time
0,1,MVK/Ambon_Apr2012_0001/00001,Ambon_Apr2012_0001,1,0.000,0.000
1,2,MVK/Ambon_Apr2012_0001/00002,Ambon_Apr2012_0001,2,1.001,1.001
2,3,MVK/Ambon_Apr2012_0001/00003,Ambon_Apr2012_0001,3,2.002,2.002
3,4,MVK/Ambon_Apr2012_0001/00004,Ambon_Apr2012_0001,4,3.003,3.003
4,5,MVK/Ambon_Apr2012_0001/00005,Ambon_Apr2012_0001,5,4.004,4.004

In [10]:
df.to_csv("./metadata_v1.csv", index=False)